# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  imageRepo: weatherapi_aks
  tag: '$(Build.BuildId)'
#create the docker image
stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
#build and push the docker image
    - task: Docker@2
      inputs:
        containerRegistry: 'bdorobek dockerhub'
        repository: 'bdorobek/weatherapi_aks'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: '$(tag)'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'K8S ARM'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: 'az account set --subscription 065c2e96-b261-41ae-b2aa-90216491219f'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'K8S ARM'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: 'az aks get-credentials --resource-group aks_tf_rg --name WeatherapiCluster'
#publish the manifest
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/s/kubernetes'
        artifact: 'manifests'
        publishLocation: 'pipeline'
- stage: Deploy
  displayName: Deploy to Dev
  dependsOn: Build
  variables:
    acrsecret: mysecret
  jobs:
  - job: Deploy
    displayName: Deploy to AKS
    pool: 
      vmImage: ubuntu-latest
    steps:
#download the manifests
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'manifests'
        targetPath: '$(Pipeline.Workspace)/manifests'

#create the secret
    - task: KubernetesManifest@0
      displayName: Create imagePullSecret
      inputs:
        action: 'createSecret'
        kubernetesServiceConnection: 'bdorobek AKS'
        namespace: 'default'
        secretType: 'dockerRegistry'
        secretName: '$(acrsecret)'
        dockerRegistryEndpoint: 'bdorobek dockerhub'
#deploy the deployment files
    - task: KubernetesManifest@0
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'bdorobek AKS'
        namespace: 'default'
        manifests: |
          $(Pipeline.Workspace)/manifests/deployment.yml
          $(Pipeline.Workspace)/manifests/setvice.yml
        imagePullSecrets: |
          $(acrsecret)
        containers: |
          $(containerRegistry)/$(acrsecret):$(tag)
  