apiVersion : apps/v1
kind: Deployment
metadata:
  name: weatherapi_aks 
spec:
  replicas: #replicaNo#
  selector:
    matchLabels:
      app: weatherapi_aks
  template:
    metadata:
      labels:
        app: weatherapi_aks 
    spec:
      containers:
        - name: weatherapi_aks 
          image: bdorobek/weatherapi_aks
          ports:
          - containerPort: 80